# Generated by Django 2.2 on 2020-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('visible_home', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='images/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='images/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
