# Generated by Django 2.2 on 2020-01-09 16:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nike', editable=False, populate_from='name', unique_with=('name',)),
            preserve_default=False,
        ),
    ]
