# Generated by Django 2.2 on 2020-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200109_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
    ]
