# Generated by Django 2.2 on 2020-01-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Information'),
        ),
    ]
